Api search book by filter
AT-PHPIntership/borrow-book pull request #108
Opened 2018-06-13 07:47 UTC by at-nale

## Description
Api search book by filter
## Reference Requirements
- Task ID: #108

## Reference Isuees
#{issue_id}

## Migrations
NO

## Impacted Areas in Application
List general components of the application that this PR will affect:

-

## SQL query and `explain`
List of all queries and attach the result of each explaining query (in text, screenshot...)

- Refer to [Using Explain with MySQL](https://viblo.asia/p/su-dung-explain-de-toi-uu-cau-lenh-mysql-BYjv44gmvxpV)

2018-06-13 08:09 UTC, at-haphan commented
LGTM

2018-06-13 08:47 UTC, ghost requested changes

2018-06-13 08:47 UTC, at-vietpham commented on app/Http/Controllers/API/BookController.php
> +        } else {
Không cần `else` ở đoạn này. Gộp chung trước `with` ở dưới là được.

2018-06-14 03:53 UTC, ghost requested changes

2018-06-14 03:53 UTC, at-vietpham commented on app/Traits/FilterTrait.php
> +                if ($this->getColummnsFilter($field) !=null) {
Lưu `$this->getColummnsFilter($field)` vào 1 biến. tránh trường hợp gọi function này 2 lần.

2018-06-14 04:08 UTC, at-vietpham commented
LGTM ⌨️

2018-06-14 04:08 UTC, merged