docs get post following user-id
AT-PHPIntership/borrow-book pull request #129
Opened 2018-06-20 07:24 UTC by at-nale

## Description
Docs get post following user-id
## Reference Requirements
- Task ID: #129

## Reference Isuees
#{issue_id}

## Migrations
NO

## Impacted Areas in Application
List general components of the application that this PR will affect:

-

## SQL query and `explain`
List of all queries and attach the result of each explaining query (in text, screenshot...)

- Refer to [Using Explain with MySQL](https://viblo.asia/p/su-dung-explain-de-toi-uu-cau-lenh-mysql-BYjv44gmvxpV)

2018-06-20 07:40 UTC, at-haytran commented
LGTM

2018-06-20 09:13 UTC, at-haytran commented
LGTM

2018-06-20 10:14 UTC, ghost requested changes

2018-06-20 10:14 UTC, at-vietpham commented on docs/api-references/post.md
> +            {
Tab 4 space thôi

2018-06-20 10:14 UTC, at-vietpham commented on docs/api-references/post.md
> +"first_page_url": "http://192.168.33.10/api/books/9/posts?page=1",
Lùi vào 1 tab

2018-06-20 10:43 UTC, ghost requested changes

2018-06-20 10:43 UTC, at-vietpham commented on docs/api-references/post.md
> +| sort | string | Sort Posts Follow Name |
Có cho phép `limit` không?
Nhiều query như vậy cần cho ví dụ cách dùng.

2018-06-21 01:57 UTC, at-haytran commented on docs/api-references/post.md
> +```
Thêm header

2018-06-21 02:43 UTC, at-haytran commented
LGTM

2018-06-21 04:19 UTC, at-vietpham commented
LGTM 🐙

2018-06-21 04:19 UTC, merged