Use api get post follow user and fix user profile
AT-PHPIntership/borrow-book pull request #162
Opened 2018-06-28 10:13 UTC by at-nale

## Description
Use api get post follow user and fix user profile
## Reference Requirements
- Task ID: #162

## Reference Isuees
#{issue_id}

## Migrations
YES | NO

## Impacted Areas in Application
List general components of the application that this PR will affect:

-

## SQL query and `explain`
List of all queries and attach the result of each explaining query (in text, screenshot...)

- Refer to [Using Explain with MySQL](https://viblo.asia/p/su-dung-explain-de-toi-uu-cau-lenh-mysql-BYjv44gmvxpV)

2018-06-28 10:21 UTC, mvn-haphan-dn reviewed
LGTM

2018-06-28 10:26 UTC, ghost requested changes

2018-06-29 03:07 UTC, mvn-haphan-dn reviewed
LGTM

2018-06-29 03:17 UTC, ghost requested changes

2018-06-29 03:17 UTC, at-vietpham commented on public/js/userPost.js
> +                    $("#"+ idpost +" .status .btn-posts-success").attr('class','btn btn-success fa fa-check').show();
Chỉ việc `show()` thôi mà đâu cần phải update lại `class`.

2018-06-29 04:26 UTC, merged