Unitest update post
AT-PHPIntership/borrow-book pull request #175
Opened 2018-07-03 06:39 UTC by at-nale

## Description
Unitest update post
## Reference Requirements
- Task ID: #175

## Reference Isuees
#{issue_id}

## Migrations
YES | NO

## Impacted Areas in Application
List general components of the application that this PR will affect:

-

## SQL query and `explain`
List of all queries and attach the result of each explaining query (in text, screenshot...)

- Refer to [Using Explain with MySQL](https://viblo.asia/p/su-dung-explain-de-toi-uu-cau-lenh-mysql-BYjv44gmvxpV)

2018-07-03 06:53 UTC, mvn-haphan-dn reviewed
LGTM

2018-07-03 06:57 UTC, ghost requested changes

2018-07-03 06:57 UTC, at-vietpham commented on app/Http/Controllers/API/PostController.php
> +    public function update(Post $post, CreatePostRequest $request)
Đây là fucntion update dùng `CreatePostRequest` dễ gây hiểu lầm. Nếu dùng chung với create thì đổi tên request thành `PostRequest`
Và PR này chỉ dùng để viết unit test, không sửa API trong này.

2018-07-03 06:57 UTC, at-vietpham commented on tests/Feature/ApiUpdatePostTest.php
> +        $response = $this->put('/api/posts/1', ['body' => '', 'post_type' => 0], ['Accept' => 'application/json', 'Authorization' => 'Bearer '.$user1->createToken('access_token')->accessToken]);
Dùng data provider.

2018-07-05 10:04 UTC, ghost approved these changes
LGTM

2018-07-05 10:07 UTC, merged