Api reset password
AT-PHPIntership/borrow-book pull request #195
Opened 2018-07-11 10:53 UTC by at-nale

## Description
Api reset password
## Reference Requirements
- Task ID: #195

## Reference Isuees
#{issue_id}

## Migrations
YES | NO

## Impacted Areas in Application
List general components of the application that this PR will affect:

-

## SQL query and `explain`
List of all queries and attach the result of each explaining query (in text, screenshot...)

- Refer to [Using Explain with MySQL](https://viblo.asia/p/su-dung-explain-de-toi-uu-cau-lenh-mysql-BYjv44gmvxpV)

2018-07-12 03:42 UTC, at-haytran commented
LGTM

2018-07-12 03:55 UTC, ghost requested changes

2018-07-12 03:55 UTC, at-vietpham commented on app/Http/Controllers/API/ResetPasswordController.php
> +    protected $redirectTo = '/home';
URL này phải có tồn tại trong route

2018-07-13 01:51 UTC, at-vietpham commented
LGTM ⭕️

2018-07-13 01:51 UTC, merged