Unitest reset password
AT-PHPIntership/borrow-book pull request #198
Opened 2018-07-13 07:25 UTC by mvn-nale-dn

## Description
Unitest reset password
## Reference Requirements
- Task ID: #198

## Reference Isuees
#{issue_id}

## Migrations
YES | NO

## Impacted Areas in Application
List general components of the application that this PR will affect:

-

## SQL query and `explain`
List of all queries and attach the result of each explaining query (in text, screenshot...)

- Refer to [Using Explain with MySQL](https://viblo.asia/p/su-dung-explain-de-toi-uu-cau-lenh-mysql-BYjv44gmvxpV)

2018-07-13 08:11 UTC, mvn-haphan-dn reviewed
LGTM

2018-07-16 04:41 UTC, ghost requested changes

2018-07-16 04:41 UTC, at-vietpham commented on tests/Feature/ResetPasswordTest.php
> +            ->assertJsonStructure($this->jsonStructure());
Test này giống như `testStatusResetPassword`. Có thể gộp chung lại.

2018-07-16 04:41 UTC, at-vietpham commented on tests/Feature/ResetPasswordTest.php
> +    public function testStructureJsonErrorToken()
Test này và `testStructureJsonErrorNotFoundEmail` có thể dùng data provider

2018-07-16 08:24 UTC, merged