Docs markdown book
AT-PHPIntership/borrow-book pull request #202
Opened 2018-07-16 09:08 UTC by at-nale

## Description
Docs markdown book
## Reference Requirements
- Task ID: #202

## Reference Isuees
#{issue_id}

## Migrations
YES | NO

## Impacted Areas in Application
List general components of the application that this PR will affect:

-

## SQL query and `explain`
List of all queries and attach the result of each explaining query (in text, screenshot...)

- Refer to [Using Explain with MySQL](https://viblo.asia/p/su-dung-explain-de-toi-uu-cau-lenh-mysql-BYjv44gmvxpV)

2018-07-16 09:22 UTC, mvn-haphan-dn reviewed
LGTM

2018-07-17 01:29 UTC, ghost requested changes

2018-07-17 01:29 UTC, at-vietpham commented on docs/api-references/favorite.md
> +```json
Define post lên data như thế nào nữa.

2018-07-17 03:04 UTC, at-vietpham commented
LGTM 🇰🇪

2018-07-17 03:05 UTC, merged