template admin index
AT-PHPIntership/borrow-book pull request #4
Opened 2018-05-14 09:57 UTC by at-haphan

## Description
Create template admin index
## Reference Requirements
- Task ID: TI-1

## Reference Isuees
#{issue_id}

## Migrations
NO

## Impacted Areas in Application
List general components of the application that this PR will affect:

-

## SQL query and `explain`
List of all queries and attach the result of each explaining query (in text, screenshot...)

- Refer to [Using Explain with MySQL](https://viblo.asia/p/su-dung-explain-de-toi-uu-cau-lenh-mysql-BYjv44gmvxpV)

2018-05-14 13:13 UTC, at-haytran commented on resources/views/admin/layouts/header.blade.php
> +</header>
tạo folder layout/partials bỏ header, footer, style, js, sidebar vào

2018-05-14 13:13 UTC, at-haytran commented on resources/views/admin/index.blade.php
> +@section('title', 'Admin Borrow Book')
Dùng Localization của laravel .
https://laravel.com/docs/5.6/localization

2018-05-14 13:13 UTC, at-haytran commented on resources/views/admin/master.blade.php
> +<!DOCTYPE html>
bỏ file này vào layout đổi tên thành admin.blade.php

2018-05-14 13:13 UTC, at-haytran commented on resources/views/admin/layouts/styles.blade.php
> +<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">
bỏ vào partials

2018-05-14 13:13 UTC, at-haytran commented on resources/views/admin/layouts/scripts.blade.php
> +<script src="bower_components/admin-lte/dist/js/demo.js"></script>
bỏ vào partials

2018-05-14 13:14 UTC, at-haytran commented on resources/views/admin/master.blade.php
> +<!DOCTYPE html>
bỏ dùng file Untitled Document please

2018-05-15 01:02 UTC, at-haytran commented on routes/web.php
> +Route::get('/admin/index', function () {
bỏ vào cái này 
Route::group(['namespace' => 'Admin', 'prefix' => 'admin' ], function(){
}

2018-05-15 02:34 UTC, ghost requested changes

2018-05-15 02:34 UTC, at-vietpham commented on .env.example
> -APP_NAME=Laravel
Tại sao em lại xóa file `.env.example`?

2018-05-15 02:34 UTC, at-vietpham commented on resources/views/admin/index.blade.php
> +@section('title', 'Admin Borrow Book')
**Admin Borrow Book** phải được define trong file lang. Em xem thêm ở đây: https://laravel.com/docs/5.6/localization

Tạo các file lang theo resource ví dụ. `user.php`, `post.php`. Những cái trừu tượng như trang admin dashboard thì có thể dùng là `admin.php`

2018-05-15 02:34 UTC, at-vietpham commented on resources/views/admin/index.blade.php
> +<div class="content-wrapper">
Có thể loại bỏ những đoạn HTML dư thừa. Chưa có implement những phần như thống kê thì cứ để trống

2018-05-15 02:34 UTC, at-vietpham commented on resources/views/admin/layouts/partials/header.blade.php
> +<header class="main-header">
Loại bỏ những đoạn HTML không cần thiết.

2018-05-15 02:34 UTC, at-vietpham commented on resources/views/admin/layouts/partials/left-bar.blade.php
> +<aside class="main-sidebar">
Như trên, loại bỏ những đoạn HTML không cần thiết.

2018-05-15 02:34 UTC, at-vietpham commented on routes/web.php
> +	Route::get('/index', function () {
Route ở đây có thể là `/admin/` không cần phải là `/admin/index`

2018-05-15 02:34 UTC, at-vietpham commented on routes/web.php
> +    	return view('admin.index');
Lùi vào 1 level.

2018-05-15 02:36 UTC, at-haphan commented on .env.example
> -APP_NAME=Laravel
do em đổi tên file thành .env nên nó mất file .env.example đi ạ

2018-05-15 06:35 UTC, ghost approved these changes

2018-05-15 06:35 UTC, at-vietpham commented
LGTM 🎲

2018-05-15 06:35 UTC, merged