Unit test search book
AT-PHPIntership/borrow-book pull request #47
Opened 2018-05-24 16:09 UTC by at-haphan

## Description
Unit test search book
## Reference Requirements
- Task ID: TI-44

## Reference Isuees

## Migrations
NO

## Impacted Areas in Application
List general components of the application that this PR will affect:

-

## SQL query and `explain`
List of all queries and attach the result of each explaining query (in text, screenshot...)

- Refer to [Using Explain with MySQL](https://viblo.asia/p/su-dung-explain-de-toi-uu-cau-lenh-mysql-BYjv44gmvxpV)

2018-05-25 01:20 UTC, at-haytran commented on resources/views/admin/books/index.blade.php
>                          <input type="text" placeholder="Search" name="search">
Bỏ vào lang

2018-05-25 02:37 UTC, at-haytran commented
LGTM

2018-05-25 03:24 UTC, ghost requested changes
Em check comment giúp anh

2018-05-25 04:20 UTC, at-haphan commented on tests/Browser/Pages/Backend/DeleteUserTest.php
> -                ->click('#table-index tbody tr:nth-child(2) .form-delete .button-delete')
do em cho ẩn nút edit vs xóa ở admin đi rồi, nên chỉ có user mới hiện ra 2 nút đó nên k cần chỉ đến dòng thứ 2 để xóa nữa ạ

2018-05-25 04:30 UTC, ghost requested changes

2018-05-25 04:30 UTC, at-vietpham commented on tests/Browser/Pages/Backend/SearchBookTest.php
> +}
Parinate cần thêm case khi click sang page khác thì danh sách ở trang list phẫn phải thuộc kết quả tìm kiếm.

2018-05-25 04:30 UTC, at-vietpham commented on tests/Browser/Pages/Backend/SearchBookTest.php
> +            'number_of_page' => 1000,
Chỉ cần difine nhữn trường cần thiết như `title` hay `author` thôi. Những trường khác để factory tự dùng faker gen ra.

2018-05-25 07:37 UTC, at-vietpham commented on tests/Browser/Pages/Backend/SearchBookTest.php
> +            $this->assertTrue($number_page == ceil((self::NUMBER_RECORD_CREATE) / (self::RECORD_LIMIT)));
Em cần dùng thêm `assertQueryStringHas` để đảm bảo url vừa có query `page=2` và `search=a`

2018-05-28 03:01 UTC, ghost approved these changes

2018-05-28 03:02 UTC, at-vietpham commented
LGTM 🏞

2018-05-28 03:02 UTC, merged