unitest delete post
AT-PHPIntership/borrow-book pull request #50
Opened 2018-05-25 04:36 UTC by at-nale

## Description
Unitest Delete Post

## Reference Requirements
- Task ID: #50

## Reference Isuees
#{issue_id}

## Migrations
YES 

## Impacted Areas in Application
List general components of the application that this PR will affect:

-

## SQL query and `explain`
List of all queries and attach the result of each explaining query (in text, screenshot...)

- Refer to [Using Explain with MySQL](https://viblo.asia/p/su-dung-explain-de-toi-uu-cau-lenh-mysql-BYjv44gmvxpV)

2018-05-25 04:56 UTC, mvn-haphan-dn reviewed
LGTM

2018-05-25 07:30 UTC, ghost requested changes

2018-05-25 07:30 UTC, at-vietpham commented on tests/Browser/Pages/Backend/DeletePostTest.php
> +        $userId = DB::table('users')->pluck('id')->all();
Tên biến nên là `$userIds`

2018-05-25 07:30 UTC, at-vietpham commented on tests/Browser/Pages/Backend/DeletePostTest.php
> +        $categoryId = DB::table('categories')->pluck('id')->all();
Đoạn này cũng vậy. Biến là array chưa nhiều ID tên biến nên là `$categoryIds`.

2018-05-25 07:30 UTC, at-vietpham commented on tests/Browser/Pages/Backend/DeletePostTest.php
> +        $faker = Faker::create();
Không nhất thiết phải khởi tạo 1 object faker chỉ để random 1 giá trị trong array. có thể dùng `array_rand()`.

2018-05-25 07:30 UTC, at-vietpham commented on tests/Browser/Pages/Backend/DeletePostTest.php
> +    public function testClickButtonDeletePost()
Tên function nên là `testCancelConfirmDelete`

2018-05-25 07:30 UTC, at-vietpham commented on tests/Browser/Pages/Backend/DeletePostTest.php
> +    public function testConfirmDeleteOnPopup()
Tên function nên là `testAcceptConfirmDelete`

2018-05-25 07:30 UTC, at-vietpham commented on tests/Browser/Pages/Backend/DeletePostTest.php
> +            $this->assertCount(1, $elements);
Đâu cần phải kiểm tra count xem đủ record hay không đâu. Việc test này đã được thực hiện ở file test list post.

2018-05-25 07:30 UTC, at-vietpham commented on tests/Browser/Pages/Backend/DeletePostTest.php
> +            $browser->click('td button.fa-trash-o')
Case này nên tạo nhiều post sau đó thực hiện xóa record thứ 2 hay 3 trong list. Rồi kiểm tra trong DB chính xác Record nào đã được xóa.

2018-05-25 07:30 UTC, at-vietpham commented on tests/Browser/Pages/Backend/DeletePostTest.php
> +            $this->assertDatabaseMissing('posts', ['deleted_at' => null]);
Như anh nói ở trên thì nên có nhiều bài post để test việc delete. Đoạn này phải check kèm theo id của post thì mới đảm bảo xóa đúng bài post.

2018-05-25 07:42 UTC, at-nale commented on tests/Browser/Pages/Backend/DeletePostTest.php
> +            $this->assertCount(1, $elements);
Anh cái này là em kiểm tra xem khi xóa thành công thì trong bảng nó sẽ mất dòng đó á anh

2018-05-28 02:13 UTC, at-vietpham commented
LGTM Ⓜ️

2018-05-28 02:13 UTC, merged