Fix Paginate when sort And unitest sort user
AT-PHPIntership/borrow-book pull request #75
Opened 2018-05-31 07:52 UTC by at-nale

## Description
Fix Paginate when sort and unitest sort user
## Reference Requirements
- Task ID: #75

## Reference Isuees
#{issue_id}

## Migrations
YES 

## Impacted Areas in Application
List general components of the application that this PR will affect:

-

## SQL query and `explain`
List of all queries and attach the result of each explaining query (in text, screenshot...)

- Refer to [Using Explain with MySQL](https://viblo.asia/p/su-dung-explain-de-toi-uu-cau-lenh-mysql-BYjv44gmvxpV)

2018-05-31 08:10 UTC, at-haphan commented on tests/Browser/Pages/Backend/SortUserTest.php
> +
xóa dòng dư

2018-05-31 08:10 UTC, at-haphan commented on tests/Browser/Pages/Backend/SortUserTest.php
> +
xóa dòng dư

2018-05-31 08:10 UTC, at-haphan commented on tests/Browser/Pages/Backend/SortUserTest.php
> +
xóa dòng dư

2018-05-31 08:10 UTC, at-haphan commented on tests/Browser/Pages/Backend/SortUserTest.php
> +                $this->assertEquals($browser->text($selector), $arraySelected[$i-1]);
$i - 1(thêm khoảng trắng)

2018-05-31 08:10 UTC, at-haphan commented on tests/Browser/Pages/Backend/SortUserTest.php
> +                $this->assertEquals($browser->text($selector), $arraySelected[$i-1]);
Thê khoảng trắng 2 bên dấu -

2018-05-31 08:10 UTC, at-haphan commented on tests/Browser/Pages/Backend/SortUserTest.php
> +                $this->assertEquals($browser->text($selector), $arraySortAsc[$i-1]);
tương tự

2018-05-31 08:10 UTC, at-haphan commented on tests/Browser/Pages/Backend/SortUserTest.php
> +                $this->assertEquals($browser->text($selector), $arraySortDesc[$i-1]);
tương tự

2018-05-31 08:10 UTC, at-haphan commented on tests/Browser/Pages/Backend/SortUserTest.php
> +
xóa 1 dòng

2018-05-31 08:17 UTC, mvn-haphan-dn reviewed
LGTM

2018-05-31 08:26 UTC, ghost requested changes

2018-05-31 08:26 UTC, at-vietpham commented on tests/Browser/Pages/Backend/SortUserTest.php
> +            sort($arraySelected);
Em không lấy data sort theo cách này. Dùng câu SQL khi thực hiện sort để có được data rồi so sánh với kết quả từ view.

2018-05-31 08:26 UTC, at-vietpham commented on tests/Browser/Pages/Backend/SortUserTest.php
> +                ->resize(1200,1600)
Thêm space trước `1600`

2018-06-01 06:41 UTC, at-huydq commented
LGTM

2018-06-01 06:41 UTC, merged